### ISSUE TITLE
Add all the skill which is removed from clients.

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/susi_skill_data#101]
**Actual Behaviour**

All hardcoded skills are removed from client. 

**Expected Behaviour**

We have to implement those skills here.

**Would you like to work on the issue?**

Yes

**Comment by chiragw15** [comment]
@amitiwary999 Please close this issue and open issues for each feature which was removed. How will people know which client and which features you are talking about. Just writing "All hardcoded skills are removed from client." and "We have to implement those skills here." is not sufficient. We have to explain what is actually expected, so that people can give ideas on how to implement them and actually implement them. Never mind just close this issue. I'll create issues for all of them.

**Comment by amitiwary999** [comment]
I am thinking of adding  all those skills here point wise.

**Comment by chiragw15** [comment]
@amitiwary999 Use template in #102 to create issues for skills 4,5,6,7 given in https://github.com/fossasia/susi_android/issues/601
